name: verify

on:
  pull_request:

jobs:
  license-check:
    name: license boilerplate check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: '1.17.x'

      - name: Install addlicense
        run: go install github.com/google/addlicense@v1.0.0

      - name: Check license headers
        run: |
          set -e
          addlicense --check --ignore **/*.yml --ignore **/*.yaml -l apache -c 'The Sigstore Authors' -v *
          git diff --exit-code
